### ISSUE TITLE
Feat: Enhance the navlinks hover animation for all navbars

### ISSUE THREAD

**Issue by Asymtode712** [Its-Aman-Yadav/Community-Site#1264]
### Describe the feature

I want to enhance the hover for navlinks of navbar present on each page by adding new hover animations as the video given below

### Add ScreenShots

https://github.com/user-attachments/assets/22ceaa50-9361-469b-b70e-81be481a2345

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@Its-Aman-Yadav @Kalivarapubindusree please assign me this issue

**Comment by Kalivarapubindusree** [comment]
Now it is fine with the hover effect and please make sure the alignment of the website  is good in mobile view also. @Asymtode712

**Comment by Asymtode712** [comment]
@Kalivarapubindusree So I should implement the hover effect like the above video?

**Comment by Kalivarapubindusree** [comment]
No it's already there u can improve alignments in the website so that UX will be good in the mobile view
![Screenshot_2024-07-28-12-11-27-79_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/4d58c949-4174-46fc-8f7d-6a25a7e8c637)
See this pic if u want to contribute please make this in good manner
